//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionYousef.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=ElectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<APPLICATION> APPLICATIONS { get; set; }
        public virtual DbSet<ContactForm> ContactForms { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Debate> Debates { get; set; }
        public virtual DbSet<ElectionAdvertisement> ElectionAdvertisements { get; set; }
        public virtual DbSet<localList> localLists { get; set; }
        public virtual DbSet<PartyCandidate> PartyCandidates { get; set; }
        public virtual DbSet<PartyList> PartyLists { get; set; }
        public virtual DbSet<PayPalPayment> PayPalPayments { get; set; }
        public virtual DbSet<PayPalPayments_APPLICATIONS> PayPalPayments_APPLICATIONS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<localCandidate> localCandidates { get; set; }
    }
}
