//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionYousef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localCandidate
    {
        public int National_ID { get; set; }
        public string Candidate_Name { get; set; }
        public string Type_of_Chair { get; set; }
        public string List_Name { get; set; }
        public string Counter { get; set; }
        public string picture { get; set; }
        public int List_ID { get; set; }
    }
}
