//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionYousef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyCandidate
    {
        public int ID { get; set; }
        public int National_ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public int PartyLIST_ID { get; set; }
        public string picture { get; set; }
    }
}
