//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionYousef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalPayments_APPLICATIONS
    {
        public int ID { get; set; }
        public int APPLICATION_ID { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
    }
}
